name: Deploy Supabase Functions

on:
  push:
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
    branches: [ main ]
  workflow_dispatch:
    inputs:
      function_name:
        description: 'Specific function to deploy (leave empty to deploy all)'
        required: false
        type: string

jobs:
  deploy-functions:
    name: Deploy Supabase Functions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify Supabase CLI installation
        run: supabase --version

      - name: Deploy Supabase Functions
        working-directory: ./supabase
        run: |
          # Link to the remote project
          echo "Linking to Supabase project..."
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          # Deploy functions (specific or all)
          if [[ -n "${{ github.event.inputs.function_name }}" ]]; then
            echo "Deploying specific function: ${{ github.event.inputs.function_name }}"
            supabase functions deploy ${{ github.event.inputs.function_name }} --verify-jwt false
          else
            echo "Deploying all Supabase functions..."
            supabase functions deploy --verify-jwt false
          fi
          
          echo "✅ Supabase functions deployed successfully"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: List deployed functions
        working-directory: ./supabase
        run: |
          echo "Current deployed functions:"
          supabase functions list
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        continue-on-error: true

      - name: Test deployed functions (basic health check)
        working-directory: ./supabase
        run: |
          echo "Running basic health checks on deployed functions..."
          
          # Get the function URLs (this is a simple check that functions are accessible)
          # Note: Actual health checks would depend on your function implementations
          echo "Functions are deployed and accessible via Supabase Edge Runtime"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        continue-on-error: true
